// <auto-generated />
using System;
using Hearth.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hearth.Core.Migrations
{
    [DbContext(typeof(HearthDbContext))]
    [Migration("20260812162209_user-and-roles")]
    partial class userandroles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Hearth.Core.Models.Finance.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Account_Number")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Balance_Available")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Balance_Current")
                        .HasColumnType("TEXT");

                    b.Property<string>("BankId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Inital_Date_Requested")
                        .HasColumnType("TEXT");

                    b.Property<string>("Institution_Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Institution_Name")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Is_Open")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Item_Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Last_Date_Requested")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Last_Modified")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mask")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Offical_Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Request_Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subtype")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Hearth.Core.Models.Finance.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Asset_Type")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Compound_Rate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Expected_Growth_Or_Decay")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LoanId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Purchase_Date")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Purchase_Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("Hearth.Core.Models.Finance.Bank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Access_Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BankId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Institution_Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Request_Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Banks");
                });

            modelBuilder.Entity("Hearth.Core.Models.Finance.BankCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Debit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hex_Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ignore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BankCategories");
                });

            modelBuilder.Entity("Hearth.Core.Models.Finance.Loan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Amortized")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Compound")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Downpayment")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Due_Date")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Interest_Paid")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Interest_Rate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Loan_Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Payment_Frequency")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Principal")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Principal_Paid")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Start_Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("Term")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Loans");
                });

            modelBuilder.Entity("Hearth.Core.Models.Finance.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Account_Owner")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Authorized_Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Authorized_Datetime")
                        .HasColumnType("TEXT");

                    b.Property<string>("By_Order_Of")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Check_Number")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Confidence_Level")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Counter_Party_Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Datetime")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Iso_Currency_Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("Lat")
                        .HasColumnType("REAL");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Logo_Url")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Lon")
                        .HasColumnType("REAL");

                    b.Property<string>("Merchant_Entity_Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Merchant_Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Payee")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Payer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Payment_Channel")
                        .HasColumnType("TEXT");

                    b.Property<string>("Payment_Method")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Payment_Processor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Pending")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Pending_Transaction_Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Personal_Finance_Category_Confidence_Level")
                        .HasColumnType("TEXT");

                    b.Property<string>("Personal_Finance_Category_Detailed")
                        .HasColumnType("TEXT");

                    b.Property<string>("Personal_Finance_Category_Icon_Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Personal_Finance_Category_Primary")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Plaid_Category_Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Postal_Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PpdId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Reference_Number")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Store_Number")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Transaction_Code")
                        .HasColumnType("TEXT");

                    b.Property<string>("Transaction_Type")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Unofficial_Currency_Code")
                        .HasColumnType("TEXT");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Hearth.Core.Models.Finance.TransactionCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hex_Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ignore")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Income")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Is_Need")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TransactionCategories");
                });

            modelBuilder.Entity("Hearth.Core.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Hearth.Core.Models.Rule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RuleType")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Rules");

                    b.HasDiscriminator<string>("RuleType").HasValue("Rule");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Hearth.Core.Models.RuleCondition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Match")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RuleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RuleId");

                    b.ToTable("RuleConditions");
                });

            modelBuilder.Entity("Hearth.Core.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Hearth.Core.Models.Finance.BankCategoryRule", b =>
                {
                    b.HasBaseType("Hearth.Core.Models.Rule");

                    b.Property<int>("BankCategoryId")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("BankCategoryRule");
                });

            modelBuilder.Entity("Hearth.Core.Models.Finance.TransactionCategoryRule", b =>
                {
                    b.HasBaseType("Hearth.Core.Models.Rule");

                    b.Property<int>("TransactionCategoryId")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("TransactionCategoryRule");
                });

            modelBuilder.Entity("Hearth.Core.Models.RuleCondition", b =>
                {
                    b.HasOne("Hearth.Core.Models.Rule", null)
                        .WithMany("RuleConditions")
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Hearth.Core.Models.User", b =>
                {
                    b.HasOne("Hearth.Core.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Hearth.Core.Models.Rule", b =>
                {
                    b.Navigation("RuleConditions");
                });
#pragma warning restore 612, 618
        }
    }
}
