// <auto-generated />
using System;
using Hearth.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hearth.Core.Migrations
{
    [DbContext(typeof(HearthDbContext))]
    [Migration("20260824192438_added-hex-color-to-bank-account")]
    partial class addedhexcolortobankaccount
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Hearth.Core.Models.Finance.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Account_Id")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Bank_Item_Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("HexColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsOpen")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mask")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Official_Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subtype")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Hearth.Core.Models.Finance.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Asset_Type")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Compound_Rate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Expected_Growth_Or_Decay")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LoanId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Purchase_Date")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Purchase_Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("Hearth.Core.Models.Finance.Bank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Access_Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("InitalDateRequested")
                        .HasColumnType("TEXT");

                    b.Property<string>("Institution_Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Item_Id")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastDateRequested")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("Request_Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Banks");
                });

            modelBuilder.Entity("Hearth.Core.Models.Finance.BankCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Debit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hex_Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ignore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BankCategories");
                });

            modelBuilder.Entity("Hearth.Core.Models.Finance.Loan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Amortized")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Compound")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Downpayment")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Due_Date")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Interest_Paid")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Interest_Rate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Loan_Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Payment_Frequency")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Principal")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Principal_Paid")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Start_Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("Term")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Loans");
                });

            modelBuilder.Entity("Hearth.Core.Models.Finance.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Account_Id")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Account_Owner")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Authorized_Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Authorized_Datetime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Check_Number")
                        .HasColumnType("TEXT");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Datetime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Iso_Currency_Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Logo_Url")
                        .HasColumnType("TEXT");

                    b.Property<string>("Merchant_Category_Code")
                        .HasColumnType("TEXT");

                    b.Property<string>("Merchant_Entity_Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Merchant_Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Payment_Channel")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Pending")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Pending_Transaction_Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Personal_Finance_Category_Icon_Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Transaction_Code")
                        .HasColumnType("TEXT");

                    b.Property<string>("Transaction_Id")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Transaction_Type")
                        .HasColumnType("TEXT");

                    b.Property<string>("Unofficial_Currency_Code")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Hearth.Core.Models.Finance.TransactionCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hex_Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ignore")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Income")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Is_Need")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TransactionCategories");
                });

            modelBuilder.Entity("Hearth.Core.Models.Finance.TransactionSyncRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Has_More")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Item_Id")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Next_Cursor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Request_Id")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Transactions_Update_Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Write_Date")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TransactionSyncRecords");
                });

            modelBuilder.Entity("Hearth.Core.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Hearth.Core.Models.Rule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RuleType")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Rules");

                    b.HasDiscriminator<string>("RuleType").HasValue("Rule");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Hearth.Core.Models.RuleCondition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Match")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RuleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RuleId");

                    b.ToTable("RuleConditions");
                });

            modelBuilder.Entity("Hearth.Core.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Hearth.Core.Models.Finance.BankCategoryRule", b =>
                {
                    b.HasBaseType("Hearth.Core.Models.Rule");

                    b.Property<int>("BankCategoryId")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("BankCategoryRule");
                });

            modelBuilder.Entity("Hearth.Core.Models.Finance.TransactionCategoryRule", b =>
                {
                    b.HasBaseType("Hearth.Core.Models.Rule");

                    b.Property<int>("TransactionCategoryId")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("TransactionCategoryRule");
                });

            modelBuilder.Entity("Hearth.Core.Models.Finance.Account", b =>
                {
                    b.OwnsOne("Hearth.Core.Models.Finance.ValueObjects.AccountBalances", "Balances", b1 =>
                        {
                            b1.Property<int>("AccountId")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal?>("Available")
                                .HasColumnType("TEXT")
                                .HasColumnName("Balances_Available");

                            b1.Property<decimal>("Current")
                                .HasColumnType("TEXT")
                                .HasColumnName("Balances_Current");

                            b1.Property<string>("Iso_Currency_Code")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Balances_Iso_Currency_Code");

                            b1.Property<decimal?>("Limit")
                                .HasColumnType("TEXT")
                                .HasColumnName("Balances_Limit");

                            b1.Property<string>("Unofficial_Currency_Code")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Balances_Unofficial_Currency_Code");

                            b1.HasKey("AccountId");

                            b1.ToTable("Accounts");

                            b1.WithOwner()
                                .HasForeignKey("AccountId");
                        });

                    b.Navigation("Balances");
                });

            modelBuilder.Entity("Hearth.Core.Models.Finance.Transaction", b =>
                {
                    b.OwnsMany("Hearth.Core.Models.Finance.ValueObjects.TransactionCounterparty", "Counterparties", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Confidence_Level")
                                .HasColumnType("TEXT")
                                .HasColumnName("Confidence_Level");

                            b1.Property<string>("Entity_Id")
                                .HasColumnType("TEXT")
                                .HasColumnName("Entity_Id");

                            b1.Property<string>("Logo_Url")
                                .HasColumnType("TEXT")
                                .HasColumnName("Logo_Url");

                            b1.Property<string>("Name")
                                .HasColumnType("TEXT")
                                .HasColumnName("Name");

                            b1.Property<int>("TransactionId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Type")
                                .HasColumnType("TEXT")
                                .HasColumnName("Type");

                            b1.Property<string>("Website")
                                .HasColumnType("TEXT")
                                .HasColumnName("Website");

                            b1.HasKey("Id");

                            b1.HasIndex("TransactionId");

                            b1.ToTable("TransactionCounterparties", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("TransactionId");
                        });

                    b.OwnsOne("Hearth.Core.Models.Finance.ValueObjects.TransactionLocation", "Location", b1 =>
                        {
                            b1.Property<int>("TransactionId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Address")
                                .HasColumnType("TEXT")
                                .HasColumnName("Location_Address");

                            b1.Property<string>("City")
                                .HasColumnType("TEXT")
                                .HasColumnName("Location_City");

                            b1.Property<string>("Country")
                                .HasColumnType("TEXT")
                                .HasColumnName("Location_Country");

                            b1.Property<double?>("Lat")
                                .HasColumnType("REAL")
                                .HasColumnName("Location_Lat");

                            b1.Property<double?>("Lon")
                                .HasColumnType("REAL")
                                .HasColumnName("Location_Lon");

                            b1.Property<string>("Postal_Code")
                                .HasColumnType("TEXT")
                                .HasColumnName("Location_Postal_Code");

                            b1.Property<string>("Region")
                                .HasColumnType("TEXT")
                                .HasColumnName("Location_Region");

                            b1.Property<string>("Store_Number")
                                .HasColumnType("TEXT")
                                .HasColumnName("Location_Store_Number");

                            b1.HasKey("TransactionId");

                            b1.ToTable("Transactions");

                            b1.WithOwner()
                                .HasForeignKey("TransactionId");
                        });

                    b.OwnsOne("Hearth.Core.Models.Finance.ValueObjects.TransactionPaymentMeta", "Payment_Meta", b1 =>
                        {
                            b1.Property<int>("TransactionId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("By_Order_Of")
                                .HasColumnType("TEXT")
                                .HasColumnName("PaymentMeta_By_Order_Of");

                            b1.Property<string>("Payee")
                                .HasColumnType("TEXT")
                                .HasColumnName("PaymentMeta_Payee");

                            b1.Property<string>("Payer")
                                .HasColumnType("TEXT")
                                .HasColumnName("PaymentMeta_Payer");

                            b1.Property<string>("Payment_Method")
                                .HasColumnType("TEXT")
                                .HasColumnName("PaymentMeta_Payment_Method");

                            b1.Property<string>("Payment_Processor")
                                .HasColumnType("TEXT")
                                .HasColumnName("PaymentMeta_Payment_Processor");

                            b1.Property<string>("Ppd_Id")
                                .HasColumnType("TEXT")
                                .HasColumnName("PaymentMeta_Ppd_Id");

                            b1.Property<string>("Reason")
                                .HasColumnType("TEXT")
                                .HasColumnName("PaymentMeta_Reason");

                            b1.Property<string>("Reference_Number")
                                .HasColumnType("TEXT")
                                .HasColumnName("PaymentMeta_Reference_Number");

                            b1.HasKey("TransactionId");

                            b1.ToTable("Transactions");

                            b1.WithOwner()
                                .HasForeignKey("TransactionId");
                        });

                    b.OwnsOne("Hearth.Core.Models.Finance.ValueObjects.TransactionPersonalFinanceCategory", "Personal_Finance_Category", b1 =>
                        {
                            b1.Property<int>("TransactionId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Confidence_Level")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Detailed")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Primary")
                                .HasColumnType("TEXT")
                                .HasColumnName("PersonalFinanceCategory_Confidence_Level");

                            b1.HasKey("TransactionId");

                            b1.ToTable("Transactions");

                            b1.WithOwner()
                                .HasForeignKey("TransactionId");
                        });

                    b.Navigation("Counterparties");

                    b.Navigation("Location");

                    b.Navigation("Payment_Meta");

                    b.Navigation("Personal_Finance_Category");
                });

            modelBuilder.Entity("Hearth.Core.Models.RuleCondition", b =>
                {
                    b.HasOne("Hearth.Core.Models.Rule", null)
                        .WithMany("RuleConditions")
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Hearth.Core.Models.User", b =>
                {
                    b.HasOne("Hearth.Core.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Hearth.Core.Models.Rule", b =>
                {
                    b.Navigation("RuleConditions");
                });
#pragma warning restore 612, 618
        }
    }
}
