// <auto-generated />
using System;
using Hearth.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hearth.Core.Migrations
{
    [DbContext(typeof(HearthDbContext))]
    partial class HearthDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Hearth.Core.Models.Finance.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Account_Number")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Balance_Available")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Balance_Current")
                        .HasColumnType("TEXT");

                    b.Property<string>("BankId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Inital_Date_Requested")
                        .HasColumnType("TEXT");

                    b.Property<string>("Institution_Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Institution_Name")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Is_Open")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Item_Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Last_Date_Requested")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Last_Modified")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mask")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Offical_Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Request_Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subtype")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Hearth.Core.Models.Finance.Bank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Access_Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BankId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Institution_Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Request_Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Banks");
                });

            modelBuilder.Entity("Hearth.Core.Models.Finance.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Account_Owner")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Authorized_Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Authorized_Datetime")
                        .HasColumnType("TEXT");

                    b.Property<string>("By_Order_Of")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Check_Number")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Confidence_Level")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Counter_Party_Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Datetime")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Iso_Currency_Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("Lat")
                        .HasColumnType("REAL");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Logo_Url")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Lon")
                        .HasColumnType("REAL");

                    b.Property<string>("Merchant_Entity_Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Merchant_Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Payee")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Payer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Payment_Channel")
                        .HasColumnType("TEXT");

                    b.Property<string>("Payment_Method")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Payment_Processor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Pending")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Pending_Transaction_Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Personal_Finance_Category_Confidence_Level")
                        .HasColumnType("TEXT");

                    b.Property<string>("Personal_Finance_Category_Detailed")
                        .HasColumnType("TEXT");

                    b.Property<string>("Personal_Finance_Category_Icon_Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Personal_Finance_Category_Primary")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Plaid_Category_Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Postal_Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PpdId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Reference_Number")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Store_Number")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Transaction_Code")
                        .HasColumnType("TEXT");

                    b.Property<string>("Transaction_Type")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Unofficial_Currency_Code")
                        .HasColumnType("TEXT");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
